Cae 118 compute learning walk summaries
BetterLesson/Betterlesson-LearningWalk-API pull request #15
Opened 2022-11-14 21:51 UTC by rishipisipati

## Checklist

#### Required
- [ ] I ran the CI build script to ensure that the code passes the following
    - Unit tests
    - Integration tests
    - Linting rules
- [ ] I ran the E2E test suite locally to ensure that no regressions were introduced

#### Optional
- [ ] My PR contains a DB schema change
    - Reviewers pay special attention to queries/indices when this box is checked
- [ ] My PR is dependent on a change to our infrastructure
    - New SSM keys
    - IAM role updates
    - ETC
- [ ] My pull request is fewer than 400 lines of code

## Purpose

* **What is the context of this pull request? Why is it being done?** **required*
This PR marks a user's submission as completed, and computes a classroom and learning walk summary for each set of participant's response. 

* **Are there any related PRs? Link to them here.**

* **Link to any additional documentation (Jira, Google Docs, wireframes, etc.)** **required when available*
https://betterlesson.atlassian.net/browse/CAE-118
## Changes

* **How are different categories of users affected by these changes?**

* **Are there any changes that need to be called out as significant or particularly tricky?**

* **What is the recommended reading order for these changes? Where should the reviewer start?**

* **Add screenshots here for any UI changes (try to limit to the most important changes to avoid extending the page too much).**

## Release

* **Are there any special considerations for deployment?** **required*

2022-11-16 16:09 UTC, nicklundin-bl requested changes
Quick first pass. Will take a deeper review later

2022-11-16 16:09 UTC, nicklundin-bl commented on localstack/scripts/create-me-client-secret.sh
> +    --endpoint-url ${ENDPOINT}
We dont need this here. Remove this file and check it into the new submodule repo if necessary

2022-11-16 16:09 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/learningwalk/config/MyClientCredentialsConfig.java
> +  @Value(value = "${me.client-secret-ssm-key}")
If its not being used, just remove it. Dead code is generally bad

2022-11-16 16:09 UTC, nicklundin-bl commented on src/main/resources/application-local.properties
> +user-service-base-url = https://app.dev.cluster.betterlesson.io
Wrong url

2022-11-16 16:09 UTC, nicklundin-bl commented on src/test/java/com/betterlesson/learningwalk/testfiles/learningWalkClassroomSummary.json
> +        "firstName": "Ellie",
Can you move these testfiles to the `src/test/resources/test-data` dir? Generally speaking `srs/main/java` and `src/test/java` should only contain java files. Everything else should go in the resources dir

2022-11-16 20:13 UTC, nicklundin-bl requested changes

2022-11-16 21:37 UTC, rishipisipati commented on src/main/java/com/betterlesson/learningwalk/learningwalk/services/LearningWalkReportingService.java
> +        });
Leaving this here for now, we can get back to it later.

2022-11-17 13:10 UTC, rishipisipati commented on src/main/java/com/betterlesson/learningwalk/learningwalk/services/LearningWalkReportingService.java
> +  @Transactional(isolation = Isolation.SERIALIZABLE, propagation = Propagation.REQUIRES_NEW)
A bit of clarity on why this is needed:

Transactional annotations use the Required propogation by default. What that means in a code calling context is the following:

`
 @Transactional
 functionA() {
  // do some stuff here 
  functionB()
 }

@Transactional
functionB() {

}
`

When functionB is called by functionA, it is called within the same transaction as transaction 

So the transaction would look something like this
`
Begin TransactionFromA
  transactionACode
  transactionBCode
  commitEverything() 
END transactionFromA
`
Since the isolation levels of the transaction below should be set to 'SERIALIZABLE' to prevent race conditions, we cannot have it be called in the context of the first transaction since transactionA has a different isolation level. 

As for why this method is set to public, Transactional annotations are ignored on private methods. We need both the propogation and the isolation levels to match for the code to execute reliably.

I will add a note here to never call this function from anywhere else outside of the first transaction's context.

2022-11-17 13:20 UTC, rishipisipati commented on src/main/java/com/betterlesson/learningwalk/learningwalk/services/LearningWalkReportingService.java
> +  @Transactional(isolation = Isolation.SERIALIZABLE, propagation = Propagation.REQUIRES_NEW)
If you dislike this, we have another alternative.

Split the functionality of this endpoint into two endpoints.

1. SubmitObservation
2. ComputeLearningWalkSummary

computeLearningWalkSummary would then fetch a list of observations that are completed for that participant as an input and resume as usual. This would place a lock on the learning_walk_observations table for the completed observations, but that shouldn't be an issue since those should now no longer be editable.

2022-11-17 18:10 UTC, rishipisipati commented on src/test/java/com/betterlesson/learningwalk/services/LearningWalkServiceTests.java
> -  @Test
These functions being were moved to LearningWalkReportingService. Moved the tests there as well.

2022-11-17 18:41 UTC, nicklundin-bl approved these changes

2022-11-17 19:07 UTC, merged