Cae 111 create learning walk endpoint
BetterLesson/Betterlesson-LearningWalk-API pull request #6
Opened 2022-11-01 14:08 UTC by rishipisipati

## Checklist

#### Required
- [ ] I ran the CI build script to ensure that the code passes the following
    - Unit tests
    - Integration tests
    - Linting rules
- [ ] I ran the E2E test suite locally to ensure that no regressions were introduced

#### Optional
- [ ] My PR contains a DB schema change
    - Reviewers pay special attention to queries/indices when this box is checked
- [ ] My PR is dependent on a change to our infrastructure
    - New SSM keys
    - IAM role updates
    - ETC
- [ ] My pull request is fewer than 400 lines of code

## Purpose

* **What is the context of this pull request? Why is it being done?** **required*
This PR encompasses the following tasks

1. Endpoint for fetching learning walk from event session id.
2. Endpoint for fetching learning walk from external learning walk id.
3. Endpoint to generate a learning walk given an event session and outcome

* **Are there any related PRs? Link to them here.**

* **Link to any additional documentation (Jira, Google Docs, wireframes, etc.)** **required when available*
https://betterlesson.atlassian.net/browse/CAE-111
https://betterlesson.atlassian.net/browse/CAE-113

## Changes

* **How are different categories of users affected by these changes?**

* **Are there any changes that need to be called out as significant or particularly tricky?**

* **What is the recommended reading order for these changes? Where should the reviewer start?**

* **Add screenshots here for any UI changes (try to limit to the most important changes to avoid extending the page too much).**

## Release

* **Are there any special considerations for deployment?** **required*

2022-11-01 14:12 UTC, rishipisipati commented on src/main/java/com/betterlesson/learningwalk/utility/security/JWTDecodeService.java
> +package com.betterlesson.learningwalk.utility.security;
Open to a better implementation here. 

As for why are we not checking facilitator or admin roles in this layer, it's because there are no roles to infer from in the JWT. The call to fetch outcome data from the lab is protected by this layer, however.

2022-11-01 14:48 UTC, nicklundin-bl requested changes
Overall looks good. I didnt check the tables/indexes because it looks like a lot of them are already there?

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/errors/exceptions/LearningWalkClassroomsNotFound.java
> +          "Learning walk classrooms not found for learning walk id :" + learningWalkId.toString(),
```suggestion
          "Learning walk classrooms not found for learning walk id: " + learningWalkId.toString(),
          "Learning walk classrooms not found for learning walk id: " + learningWalkId.toString(),
```

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/errors/exceptions/LearningWalkClassroomsNotFound.java
> +          ApiErrorCode.AuthFailure,
```suggestion
          ApiErrorCode.EntityNotFound,
```

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/errors/exceptions/LearningWalkNotFoundException.java
> +        "Learning walk not found for event session id :" + eventSessionId.toString(),
```suggestion
        "Learning walk not found for event session id: " + eventSessionId.toString(),
        "Learning walk not found for event session id: " + eventSessionId.toString(),
```

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/errors/exceptions/LearningWalkNotFoundException.java
> +        "Learning walk not found for event session id :" + learningWalkExternalId.toString(),
```suggestion
        "Learning walk not found for event session id: " + learningWalkExternalId.toString(),
        "Learning walk not found for event session id: " + learningWalkExternalId.toString(),
```

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/learningwalk/learningwalk/controllers/LearningWalkController.java
> +  }
I dont see this endpoint in the design doc. Did we change from our original design?

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/learningwalk/learningwalk/controllers/LearningWalkController.java
> +  }
Looks like we changed the route around a bit here. Any reason for that?

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/learningwalk/learningwalk/controllers/LearningWalkController.java
> +}
Run the formatter

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/learningwalk/learningwalk/models/data/LearningWalk.java
> +  private String focusArea;
Focus area is not in the data design. Do we need this here?

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/learningwalk/learningwalk/controllers/LearningWalkController.java
> +  }
Also, any reason were using the verb `generateLearningWalk` here? Typically with crud operations we can stick to `Create`, `Read`, `Update`, `Delete`, and `Save` as the defacto verbage. If its doing something other than "Standard" crud then choosing a different verb (such as `generate`) is a GOOD idea because it will signal to the reader that something else is going on. If its standard crud, then Id stick to one of those 5 for the service + controller method names

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/learningwalk/learningwalk/models/responses/LearningWalkResponse.java
> +  private String topicDescription;
Looks like we changed `outcome` to `topic` from the data design. Is this intentional? If so can we update the data design? Have we looped in brent to this change?

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/learningwalk/learningwalk/services/LabService.java
> +}
Can you make sure we have a test for this using the mockwebserver pattern? 

Here is an example of this pattern in action in the jobs service

https://github.com/BetterLesson/BetterLesson-Jobs-API/blob/main/src/test/java/com/betterlesson/jobs/salesforce/cohorts/jobs/SyncCohortToUserServiceJobTests.java#L170

This pattern allows us to test HTTP calls as a black box. This means we dont have to mock/stub any of the internals and we can swap out the underlying http libraries without rewriting tests.

To do this, you'll need to 
- add the mock web server dependency in the gradle file
  - https://github.com/BetterLesson/BetterLesson-Jobs-API/blob/main/build.gradle#L85 
- copy over some helper code I wrote
  - https://github.com/BetterLesson/BetterLesson-Jobs-API/tree/main/src/test/java/com/betterlesson/jobs/_testutil/webserver

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/resources/application-live.properties
> +lab-base-url = https://dev.betterlesson.com
Wrong url

2022-11-01 14:48 UTC, nicklundin-bl commented on src/main/resources/application-staging.properties
> +lab-base-url = https://dev.betterlesson.com
Wrong url

2022-11-01 15:10 UTC, rishipisipati commented on src/main/java/com/betterlesson/learningwalk/learningwalk/controllers/LearningWalkController.java
> +  }
The base route is set to api/v1/learning-walks/

It seems like a good extension here.

2022-11-01 15:13 UTC, rishipisipati commented on src/main/java/com/betterlesson/learningwalk/learningwalk/models/responses/LearningWalkResponse.java
> +  private String topicDescription;
I did it so that we remain more consistent with the verbiage we're utilizing in the learning walks. 

tables are named topic_ids, but responses are returning outcomeId

2022-11-01 15:20 UTC, rishipisipati commented on src/main/java/com/betterlesson/learningwalk/learningwalk/controllers/LearningWalkController.java
> +  }
I modified the endpoint so that it no longer needed a request body. Also, the endpoint was requesting more information than necessary. Efficiency > rushed design work.

So in first API Call we fetch a list of all outcomes in the lab.

We make a selection on the dropdown, at which point we have an outcome id. After the user makes the selection, they can now call the lab and fetch data related only to the outcome they have chosen for this endpoint.

2022-11-01 15:22 UTC, rishipisipati commented on src/main/java/com/betterlesson/learningwalk/learningwalk/controllers/LearningWalkController.java
> +  }
Base route is api/v1/learning-walks, the original route doesn't make sense in context to this controller. 

So new route is GET {base-url}/api/v1/learning-walks/event-session/eventSessionId

I can move this to another controller, but it seemed like introducing unnecessary boilerplate code for the purposes of rushing.

2022-11-01 15:28 UTC, rishipisipati commented on src/main/java/com/betterlesson/learningwalk/learningwalk/models/data/LearningWalk.java
> +  private String focusArea;
That was a miss in the original design. 

![image](https://user-images.githubusercontent.com/87985030/199271899-ac2f9d84-c699-4a3e-ae75-ade627cfd2b9.png)

If you notice the capsule on top, that is the focus area

2022-11-01 15:29 UTC, rishipisipati commented on src/main/java/com/betterlesson/learningwalk/learningwalk/models/responses/LearningWalkResponse.java
> +  private String topicDescription;
I'll be sure to update the data design.

2022-11-01 15:55 UTC, rishipisipati commented on src/main/java/com/betterlesson/learningwalk/learningwalk/controllers/LearningWalkController.java
> +  }
Changed it to createLearningWalk

2022-11-01 16:32 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/learningwalk/learningwalk/controllers/LearningWalkController.java
> +  }
I think the change is okay. Can you update the design doc and loop in @brichison here?

2022-11-01 16:33 UTC, nicklundin-bl commented on src/main/java/com/betterlesson/learningwalk/learningwalk/models/data/LearningWalk.java
> +  private String focusArea;
👍

2022-11-02 14:17 UTC, nicklundin-bl approved these changes
LGTM!

2022-11-02 14:17 UTC, nicklundin-bl commented on src/test/java/com/betterlesson/learningwalk/services/LabServiceTests.java
> +    }
nit: why try/catch here? Could we not just let the exception be thrown?

2022-11-02 16:49 UTC, rishipisipati commented on src/test/java/com/betterlesson/learningwalk/services/LabServiceTests.java
> +    }
Good point. The test should fail if the code throws an exception at this point.

2022-11-02 16:50 UTC, merged